spring:
  cache:
    type: redis
    host: 172.18.0.2
    port: 6379
    redis:
      time-to-live: 60000
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
